FROM golang:1.13.8 as build-stage

WORKDIR /iloplugin/

ADD plugin-ilo .
RUN go build -i -race .

FROM ubuntu:18.04

RUN groupadd -r -g 2021 odimra
RUN  useradd -s /bin/bash -u 2021 -m -d /home/odimra -r -g odimra odimra
RUN mkdir /etc/iloplugin_config && chown odimra:odimra /etc/iloplugin_config
COPY install/Docker/dockerfiles/scripts/start_iloplugin.sh /bin/
COPY --from=build-stage /iloplugin/plugin-ilo /bin/
USER odimra:odimra
ENTRYPOINT ["/bin/start_iloplugin.sh"]

