---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: odim-ra
    unit: zookeeper
spec:
  type: ClusterIP
  selector:
    app: odim-ra
    unit: zookeeper
    parentdeployment: odim-zookeeper
  ports:
    - name: zookeeper
      port: 2281
---
