---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: zookeeper
    deployment: odim-ra
spec:
  type: ClusterIP
  selector:
    app: zookeeper
    parentdeployment: odim-ra
  ports:
    - name: zookeeper
      port: 2281
---
