apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ondisk
  name: redis-ondisk
  namespace: {{ .Values.odimra.namespace }}
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis-ondisk
