// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chassis/chassis.proto

package chassis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetChassisRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	RequestParam         string   `protobuf:"bytes,2,opt,name=requestParam,proto3" json:"requestParam,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	ResourceID           string   `protobuf:"bytes,4,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChassisRequest) Reset()         { *m = GetChassisRequest{} }
func (m *GetChassisRequest) String() string { return proto.CompactTextString(m) }
func (*GetChassisRequest) ProtoMessage()    {}
func (*GetChassisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{0}
}

func (m *GetChassisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChassisRequest.Unmarshal(m, b)
}
func (m *GetChassisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChassisRequest.Marshal(b, m, deterministic)
}
func (m *GetChassisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChassisRequest.Merge(m, src)
}
func (m *GetChassisRequest) XXX_Size() int {
	return xxx_messageInfo_GetChassisRequest.Size(m)
}
func (m *GetChassisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChassisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChassisRequest proto.InternalMessageInfo

func (m *GetChassisRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *GetChassisRequest) GetRequestParam() string {
	if m != nil {
		return m.RequestParam
	}
	return ""
}

func (m *GetChassisRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GetChassisRequest) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

type GetChassisResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetChassisResponse) Reset()         { *m = GetChassisResponse{} }
func (m *GetChassisResponse) String() string { return proto.CompactTextString(m) }
func (*GetChassisResponse) ProtoMessage()    {}
func (*GetChassisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{1}
}

func (m *GetChassisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChassisResponse.Unmarshal(m, b)
}
func (m *GetChassisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChassisResponse.Marshal(b, m, deterministic)
}
func (m *GetChassisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChassisResponse.Merge(m, src)
}
func (m *GetChassisResponse) XXX_Size() int {
	return xxx_messageInfo_GetChassisResponse.Size(m)
}
func (m *GetChassisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChassisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChassisResponse proto.InternalMessageInfo

func (m *GetChassisResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetChassisResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetChassisResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetChassisResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*GetChassisRequest)(nil), "GetChassisRequest")
	proto.RegisterType((*GetChassisResponse)(nil), "GetChassisResponse")
	proto.RegisterMapType((map[string]string)(nil), "GetChassisResponse.HeaderEntry")
}

func init() { proto.RegisterFile("proto/chassis/chassis.proto", fileDescriptor_32fd8686c648bc54) }

var fileDescriptor_32fd8686c648bc54 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x7f, 0xa5, 0xc0, 0x2f, 0x0e, 0x68, 0x74, 0xe4, 0xd0, 0x60, 0xa2, 0xa4, 0xf1, 0xc0,
	0xa9, 0x26, 0x78, 0xf0, 0xdf, 0xc1, 0x18, 0x34, 0x4a, 0xa2, 0x89, 0xd9, 0xe8, 0x03, 0x2c, 0x30,
	0x0a, 0x01, 0x77, 0x71, 0x67, 0x6b, 0xd2, 0x87, 0xf0, 0xc5, 0x7c, 0x0c, 0x9f, 0xc4, 0x74, 0x5b,
	0x42, 0x11, 0x2f, 0x9c, 0x3a, 0xf3, 0x99, 0xef, 0x74, 0xbe, 0x3b, 0xbb, 0xb0, 0x37, 0x33, 0xda,
	0xea, 0xa3, 0xc1, 0x48, 0x32, 0x8f, 0x79, 0xfe, 0x8d, 0x1c, 0x0d, 0x3f, 0x3d, 0xd8, 0xb9, 0x25,
	0xdb, 0xcd, 0xa0, 0xa0, 0xf7, 0x98, 0xd8, 0x62, 0x08, 0x75, 0x26, 0xe6, 0xb1, 0x56, 0x4f, 0x7a,
	0x42, 0x2a, 0xf0, 0x5a, 0x5e, 0x7b, 0x43, 0x2c, 0xb1, 0x54, 0x63, 0x32, 0xf9, 0xa3, 0x34, 0xf2,
	0x2d, 0x28, 0x65, 0x9a, 0x22, 0xc3, 0x6d, 0xf0, 0x9f, 0xc5, 0x7d, 0xe0, 0xbb, 0x52, 0x1a, 0xe2,
	0x3e, 0x80, 0x21, 0xd6, 0xb1, 0x19, 0x50, 0xef, 0x3a, 0x28, 0xbb, 0x42, 0x81, 0x84, 0xdf, 0x1e,
	0x60, 0xd1, 0x0f, 0xcf, 0xb4, 0x62, 0x4a, 0xdb, 0xd8, 0x4a, 0x1b, 0x73, 0x57, 0x0f, 0xc9, 0xd9,
	0xa9, 0x88, 0x02, 0xc1, 0x43, 0xd8, 0xcc, 0xb2, 0x07, 0x62, 0x96, 0xaf, 0x94, 0xbb, 0x59, 0x86,
	0x78, 0x02, 0xd5, 0x11, 0xc9, 0x21, 0x99, 0xc0, 0x6f, 0xf9, 0xed, 0x5a, 0xe7, 0x20, 0x5a, 0x1d,
	0x15, 0xdd, 0x39, 0xc5, 0x8d, 0xb2, 0x26, 0x11, 0xb9, 0x1c, 0x11, 0xca, 0x7d, 0x3d, 0x4c, 0x9c,
	0xdf, 0xba, 0x70, 0x71, 0xf3, 0x0c, 0x6a, 0x05, 0x69, 0x7a, 0xd4, 0x09, 0x25, 0xf9, 0xa6, 0xd2,
	0x10, 0x1b, 0x50, 0xf9, 0x90, 0xd3, 0x78, 0xee, 0x25, 0x4b, 0xce, 0x4b, 0xa7, 0x5e, 0xe7, 0xcb,
	0x83, 0xff, 0xf9, 0x58, 0xbc, 0x82, 0xc6, 0xc2, 0x44, 0x57, 0x4f, 0xa7, 0x34, 0xb0, 0x63, 0xad,
	0x10, 0xa3, 0x95, 0x6b, 0x69, 0xee, 0xfe, 0xe1, 0x37, 0xfc, 0x87, 0x97, 0xbf, 0x56, 0xe6, 0x76,
	0xb9, 0xce, 0x0f, 0x2e, 0x60, 0x6b, 0xc1, 0x7b, 0xea, 0x45, 0xaf, 0xd1, 0xdc, 0xaf, 0xba, 0x87,
	0x74, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x37, 0x40, 0xa5, 0x6d, 0x67, 0x02, 0x00, 0x00,
}
