// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chassis/chassis.proto

package chassis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetChassisRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	RequestParam         string   `protobuf:"bytes,2,opt,name=requestParam,proto3" json:"requestParam,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	ResourceID           string   `protobuf:"bytes,4,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChassisRequest) Reset()         { *m = GetChassisRequest{} }
func (m *GetChassisRequest) String() string { return proto.CompactTextString(m) }
func (*GetChassisRequest) ProtoMessage()    {}
func (*GetChassisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{0}
}

func (m *GetChassisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChassisRequest.Unmarshal(m, b)
}
func (m *GetChassisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChassisRequest.Marshal(b, m, deterministic)
}
func (m *GetChassisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChassisRequest.Merge(m, src)
}
func (m *GetChassisRequest) XXX_Size() int {
	return xxx_messageInfo_GetChassisRequest.Size(m)
}
func (m *GetChassisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChassisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChassisRequest proto.InternalMessageInfo

func (m *GetChassisRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *GetChassisRequest) GetRequestParam() string {
	if m != nil {
		return m.RequestParam
	}
	return ""
}

func (m *GetChassisRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GetChassisRequest) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

type GetChassisResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetChassisResponse) Reset()         { *m = GetChassisResponse{} }
func (m *GetChassisResponse) String() string { return proto.CompactTextString(m) }
func (*GetChassisResponse) ProtoMessage()    {}
func (*GetChassisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{1}
}

func (m *GetChassisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChassisResponse.Unmarshal(m, b)
}
func (m *GetChassisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChassisResponse.Marshal(b, m, deterministic)
}
func (m *GetChassisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChassisResponse.Merge(m, src)
}
func (m *GetChassisResponse) XXX_Size() int {
	return xxx_messageInfo_GetChassisResponse.Size(m)
}
func (m *GetChassisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChassisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChassisResponse proto.InternalMessageInfo

func (m *GetChassisResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetChassisResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetChassisResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetChassisResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateChassisRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,2,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChassisRequest) Reset()         { *m = CreateChassisRequest{} }
func (m *CreateChassisRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChassisRequest) ProtoMessage()    {}
func (*CreateChassisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{2}
}

func (m *CreateChassisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChassisRequest.Unmarshal(m, b)
}
func (m *CreateChassisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChassisRequest.Marshal(b, m, deterministic)
}
func (m *CreateChassisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChassisRequest.Merge(m, src)
}
func (m *CreateChassisRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChassisRequest.Size(m)
}
func (m *CreateChassisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChassisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChassisRequest proto.InternalMessageInfo

func (m *CreateChassisRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *CreateChassisRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type DeleteChassisRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteChassisRequest) Reset()         { *m = DeleteChassisRequest{} }
func (m *DeleteChassisRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChassisRequest) ProtoMessage()    {}
func (*DeleteChassisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{3}
}

func (m *DeleteChassisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteChassisRequest.Unmarshal(m, b)
}
func (m *DeleteChassisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteChassisRequest.Marshal(b, m, deterministic)
}
func (m *DeleteChassisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteChassisRequest.Merge(m, src)
}
func (m *DeleteChassisRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteChassisRequest.Size(m)
}
func (m *DeleteChassisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteChassisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteChassisRequest proto.InternalMessageInfo

func (m *DeleteChassisRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *DeleteChassisRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type UpdateChassisRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateChassisRequest) Reset()         { *m = UpdateChassisRequest{} }
func (m *UpdateChassisRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateChassisRequest) ProtoMessage()    {}
func (*UpdateChassisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fd8686c648bc54, []int{4}
}

func (m *UpdateChassisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChassisRequest.Unmarshal(m, b)
}
func (m *UpdateChassisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChassisRequest.Marshal(b, m, deterministic)
}
func (m *UpdateChassisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChassisRequest.Merge(m, src)
}
func (m *UpdateChassisRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateChassisRequest.Size(m)
}
func (m *UpdateChassisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChassisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChassisRequest proto.InternalMessageInfo

func (m *UpdateChassisRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *UpdateChassisRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *UpdateChassisRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func init() {
	proto.RegisterType((*GetChassisRequest)(nil), "GetChassisRequest")
	proto.RegisterType((*GetChassisResponse)(nil), "GetChassisResponse")
	proto.RegisterMapType((map[string]string)(nil), "GetChassisResponse.HeaderEntry")
	proto.RegisterType((*CreateChassisRequest)(nil), "CreateChassisRequest")
	proto.RegisterType((*DeleteChassisRequest)(nil), "DeleteChassisRequest")
	proto.RegisterType((*UpdateChassisRequest)(nil), "UpdateChassisRequest")
}

func init() { proto.RegisterFile("proto/chassis/chassis.proto", fileDescriptor_32fd8686c648bc54) }

var fileDescriptor_32fd8686c648bc54 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x6d, 0x12, 0xb5, 0xf4, 0xaa, 0xa5, 0xbd, 0x8d, 0x10, 0x2c, 0xb4, 0x12, 0xfa, 0xe0, 0x53,
	0x0a, 0xf6, 0xa1, 0x5f, 0x94, 0xd2, 0xc6, 0xd2, 0x0a, 0x16, 0x4a, 0xa8, 0x6f, 0x7d, 0x19, 0xcd,
	0xed, 0x2a, 0x66, 0x33, 0xee, 0xcc, 0x64, 0xc1, 0x5f, 0xb0, 0x4f, 0xfb, 0x27, 0xf7, 0x97, 0x2c,
	0x99, 0xc4, 0x35, 0xd1, 0xac, 0xa0, 0xec, 0x53, 0xee, 0x9c, 0x39, 0xe7, 0xce, 0xc9, 0x9c, 0xcb,
	0xc0, 0xcb, 0x95, 0xe0, 0x8a, 0xbf, 0x9d, 0xcd, 0x99, 0x94, 0x0b, 0xb9, 0xf9, 0x7a, 0x1a, 0x75,
	0xaf, 0x0d, 0x78, 0xfe, 0x93, 0x94, 0x9f, 0x81, 0x01, 0x5d, 0x24, 0x24, 0x15, 0xba, 0xd0, 0x92,
	0x24, 0xe5, 0x82, 0xc7, 0x7f, 0xf9, 0x92, 0x62, 0xc7, 0xe8, 0x19, 0xfd, 0x27, 0x41, 0x09, 0x4b,
	0x39, 0x22, 0xa3, 0xff, 0x61, 0x82, 0x9d, 0x3b, 0x66, 0xc6, 0x29, 0x62, 0xf8, 0x0c, 0xac, 0x49,
	0x30, 0x76, 0x2c, 0xbd, 0x95, 0x96, 0xf8, 0x0a, 0x40, 0x90, 0xe4, 0x89, 0x98, 0xd1, 0x68, 0xe8,
	0xd4, 0xf4, 0x46, 0x01, 0x71, 0x6f, 0x0c, 0xc0, 0xa2, 0x1f, 0xb9, 0xe2, 0xb1, 0xa4, 0x54, 0x26,
	0x15, 0x53, 0x89, 0xf4, 0x79, 0x48, 0xda, 0x4e, 0x3d, 0x28, 0x20, 0xf8, 0x06, 0xda, 0xd9, 0xea,
	0x37, 0x49, 0xc9, 0xce, 0x28, 0x77, 0x53, 0x06, 0xf1, 0x3d, 0x34, 0xe6, 0xc4, 0x42, 0x12, 0x8e,
	0xd5, 0xb3, 0xfa, 0xcd, 0xc1, 0x6b, 0x6f, 0xff, 0x28, 0xef, 0x97, 0x66, 0xfc, 0x88, 0x95, 0x58,
	0x07, 0x39, 0x1d, 0x11, 0x6a, 0x53, 0x1e, 0xae, 0xb5, 0xdf, 0x56, 0xa0, 0xeb, 0xee, 0x47, 0x68,
	0x16, 0xa8, 0xe9, 0xaf, 0x2e, 0x69, 0x9d, 0xdf, 0x54, 0x5a, 0xa2, 0x0d, 0xf5, 0x4b, 0x16, 0x25,
	0x1b, 0x2f, 0xd9, 0xe2, 0x93, 0xf9, 0xc1, 0x70, 0xff, 0x81, 0xed, 0x0b, 0x62, 0x8a, 0x4e, 0xb8,
	0xf6, 0x1e, 0x34, 0x73, 0xfa, 0xf7, 0xd4, 0x91, 0xa9, 0x1d, 0x15, 0x21, 0x77, 0x0c, 0xf6, 0x90,
	0x22, 0x3a, 0xa9, 0x7b, 0x1e, 0x98, 0x79, 0x17, 0x98, 0x1b, 0x83, 0x3d, 0x59, 0x85, 0xec, 0x61,
	0xba, 0xed, 0xba, 0xb7, 0xf6, 0xdc, 0x0f, 0xae, 0x2c, 0x78, 0x9c, 0x1f, 0x85, 0xdf, 0xc0, 0xde,
	0x06, 0xe4, 0xf3, 0x28, 0xa2, 0x99, 0x5a, 0xf0, 0x18, 0xd1, 0xdb, 0x1b, 0xd9, 0xee, 0x8b, 0x8a,
	0x2c, 0xdd, 0x47, 0xf8, 0x75, 0x67, 0x9c, 0xf4, 0x9c, 0x1d, 0xd3, 0xe0, 0x33, 0x3c, 0xdd, 0xe2,
	0xa3, 0xf8, 0x3f, 0x3f, 0x46, 0xfc, 0x05, 0xda, 0xa5, 0xa0, 0xb1, 0xe3, 0x55, 0x05, 0x7f, 0x40,
	0x5e, 0x4a, 0x12, 0x3b, 0x5e, 0x55, 0xb2, 0x07, 0xe4, 0xa5, 0xe8, 0xb0, 0xe3, 0x55, 0x45, 0x79,
	0x8f, 0x7c, 0xda, 0xd0, 0x2f, 0xc4, 0xbb, 0xdb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x2a, 0x58,
	0xee, 0x40, 0x04, 0x00, 0x00,
}
