odimra:
  namespace:
  groupID:
  haDeploymentEnabled:
urplugin:
  imageTag: "3.4"
  urPluginRootServiceUUID:
  username:
  password:
  host: urplugin
  odimUsername:
  odimPassword:
  sentinelPrimaryName: primaryset
  logPath:
  logsOnConsole: true
