---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lenovoplugin-log-claim
  namespace: {{ .Values.odimra.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
