// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	AccountResponse
	CreateAccountRequest
	AccountRequest
	GetAccountRequest
	UpdateAccountRequest
	DeleteAccountRequest
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountResponse struct {
	StatusCode    int32             `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	StatusMessage string            `protobuf:"bytes,2,opt,name=statusMessage" json:"statusMessage,omitempty"`
	Header        map[string]string `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *AccountResponse) Reset()                    { *m = AccountResponse{} }
func (m *AccountResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()               {}
func (*AccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *AccountResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *AccountResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AccountResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateAccountRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
	RequestBody  []byte `protobuf:"bytes,2,opt,name=RequestBody,json=requestBody,proto3" json:"RequestBody,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *CreateAccountRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type AccountRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type GetAccountRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
	AccountID    string `protobuf:"bytes,2,opt,name=AccountID,json=accountID" json:"AccountID,omitempty"`
}

func (m *GetAccountRequest) Reset()                    { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()               {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *GetAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

type UpdateAccountRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
	AccountID    string `protobuf:"bytes,2,opt,name=AccountID,json=accountID" json:"AccountID,omitempty"`
	RequestBody  []byte `protobuf:"bytes,3,opt,name=RequestBody,json=requestBody,proto3" json:"RequestBody,omitempty"`
}

func (m *UpdateAccountRequest) Reset()                    { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()               {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *UpdateAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *UpdateAccountRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type DeleteAccountRequest struct {
	SessionToken string `protobuf:"bytes,1,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
	AccountID    string `protobuf:"bytes,2,opt,name=AccountID,json=accountID" json:"AccountID,omitempty"`
}

func (m *DeleteAccountRequest) Reset()                    { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()               {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *DeleteAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountResponse)(nil), "AccountResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "CreateAccountRequest")
	proto.RegisterType((*AccountRequest)(nil), "AccountRequest")
	proto.RegisterType((*GetAccountRequest)(nil), "GetAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "DeleteAccountRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Account service

type AccountClient interface {
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetAllAccounts(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetAccountServices(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAllAccounts(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/GetAllAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/GetAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccountServices(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/GetAccountServices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := grpc.Invoke(ctx, "/Account/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountServer interface {
	Create(context.Context, *CreateAccountRequest) (*AccountResponse, error)
	GetAllAccounts(context.Context, *AccountRequest) (*AccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*AccountResponse, error)
	GetAccountServices(context.Context, *AccountRequest) (*AccountResponse, error)
	Update(context.Context, *UpdateAccountRequest) (*AccountResponse, error)
	Delete(context.Context, *DeleteAccountRequest) (*AccountResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAllAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAllAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/GetAllAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAllAccounts(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAccountServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAccountServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/GetAccountServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAccountServices(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Update(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Account/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Delete(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Account_Create_Handler,
		},
		{
			MethodName: "GetAllAccounts",
			Handler:    _Account_GetAllAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Account_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountServices",
			Handler:    _Account_GetAccountServices_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Account_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Account_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x6d, 0x70, 0xe5, 0x31, 0x5f, 0x1d, 0x19, 0xc9, 0x42, 0xa8, 0xb2, 0xac, 0x1e, 0x7c,
	0xda, 0x03, 0x50, 0xa9, 0xf4, 0xd6, 0x42, 0xd5, 0xf6, 0xd0, 0x8b, 0x29, 0x52, 0x0f, 0xbd, 0x18,
	0x3c, 0x4a, 0x10, 0x96, 0x97, 0x78, 0xd7, 0x48, 0xe4, 0x57, 0xe6, 0x07, 0xe4, 0xc7, 0x44, 0xd8,
	0x26, 0x10, 0x70, 0x22, 0x82, 0x72, 0xdb, 0x7d, 0x33, 0x6f, 0xe6, 0xed, 0x7b, 0x36, 0xd4, 0x83,
	0xf9, 0x9c, 0xa7, 0xb1, 0x64, 0xab, 0x84, 0x4b, 0xee, 0xde, 0x2b, 0xd0, 0xfc, 0x96, 0x23, 0x3e,
	0x89, 0x15, 0x8f, 0x05, 0xe1, 0x47, 0x00, 0x21, 0x03, 0x99, 0x8a, 0x11, 0x0f, 0xc9, 0x56, 0x1c,
	0xc5, 0xab, 0xfa, 0x07, 0x08, 0x7e, 0x82, 0x7a, 0x7e, 0xfb, 0x43, 0x42, 0x04, 0x57, 0x64, 0xab,
	0x8e, 0xe2, 0x19, 0xfe, 0x53, 0x10, 0x07, 0xa0, 0x5f, 0x53, 0x10, 0x52, 0x62, 0x6b, 0x8e, 0xe6,
	0x99, 0xbd, 0x2e, 0x3b, 0xda, 0xc3, 0x7e, 0x65, 0xe5, 0x1f, 0xb1, 0x4c, 0x36, 0x7e, 0xd1, 0x8b,
	0x08, 0x95, 0x19, 0x0f, 0x37, 0x76, 0xc5, 0x51, 0xbc, 0x9a, 0x9f, 0x9d, 0x3b, 0x43, 0x30, 0x0f,
	0x5a, 0xb1, 0x05, 0xda, 0x92, 0x36, 0x99, 0x2e, 0xc3, 0xdf, 0x1e, 0xd1, 0x82, 0xea, 0x3a, 0x88,
	0xd2, 0x9d, 0x90, 0xfc, 0xf2, 0x55, 0xfd, 0xa2, 0xb8, 0xff, 0xc1, 0x1a, 0x25, 0x14, 0x48, 0x7a,
	0xdc, 0x7d, 0x93, 0x92, 0x90, 0xe8, 0x42, 0x6d, 0x42, 0x42, 0x2c, 0x78, 0xfc, 0x97, 0x2f, 0x29,
	0x2e, 0x86, 0xd5, 0xc4, 0x01, 0x86, 0x0e, 0x98, 0x45, 0xfb, 0xf7, 0xad, 0x22, 0x35, 0x53, 0x64,
	0x26, 0x7b, 0xc8, 0x1d, 0x40, 0xe3, 0xf5, 0x73, 0xdd, 0x29, 0x7c, 0xf8, 0x49, 0xf2, 0x02, 0x41,
	0x5d, 0x30, 0x0a, 0xd6, 0xef, 0x71, 0xf1, 0x54, 0x23, 0xd8, 0x01, 0xee, 0x2d, 0x58, 0xd3, 0x55,
	0x78, 0xd9, 0x53, 0x5f, 0x9c, 0x7c, 0x6c, 0x84, 0x76, 0x6a, 0xc4, 0x3f, 0xb0, 0xc6, 0x14, 0xd1,
	0xdb, 0xef, 0xee, 0xdd, 0xa9, 0xf0, 0xbe, 0x28, 0x63, 0x1f, 0xf4, 0x3c, 0x4c, 0x6c, 0xb3, 0xb2,
	0x54, 0x3b, 0xad, 0xe3, 0x4f, 0xcc, 0x7d, 0x87, 0x9f, 0xa1, 0xb1, 0x75, 0x3b, 0x8a, 0x8a, 0x92,
	0xc0, 0x26, 0x3b, 0x83, 0x36, 0x00, 0xd8, 0x87, 0x84, 0xc8, 0x4e, 0x12, 0x2b, 0x65, 0x0d, 0x01,
	0xf7, 0x8d, 0x13, 0x4a, 0xd6, 0x8b, 0x39, 0x9d, 0xb9, 0xb0, 0x0f, 0x7a, 0x1e, 0x1f, 0xb6, 0x59,
	0x59, 0x8e, 0xcf, 0x91, 0x72, 0xdf, 0xb1, 0xcd, 0xca, 0x02, 0x28, 0x23, 0xcd, 0xf4, 0xec, 0xcf,
	0xef, 0x3f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xdd, 0x8d, 0xc6, 0x0a, 0x04, 0x00, 0x00,
}
