apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odimra-role
  namespace: {{ .Values.odimra.namespace }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
