//(C) Copyright [2020] Hewlett Packard Enterprise Development LP
//
//Licensed under the Apache License, Version 2.0 (the "License"); you may
//not use this file except in compliance with the License. You may obtain
//a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
//License for the specific language governing permissions and limitations
// under the License.

//Package lpresponse ...
package lpresponse

//Login struct definition
type Login struct {
	Token string `json:"Token"`
}

// PluginResponse struct definition
type PluginResponse struct {
	PublicKey []byte `json:"publicKey"`
	Token     string `json:"token"`
}

var (
	// ServerToken is the token generated by odimra
	ServerToken string
	// PluginToken is the token generated by Plugin
	PluginToken string
)
