apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha-inmemory
  name: redis-ha-inmemory
  namespace: {{ .Values.odimra.namespace }}
spec:
  ports:
    - name: redis
      port: 6379
    - name: redis-sentinel
      port: 26379
  selector:
    app: redis-ha-inmemory
