apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha-inmemory-sentinel
  name: redis-ha-inmemory-sentinel-headless
  namespace: {{ .Values.odimra.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis-sentinel
      port: 26379
  selector:
    app: redis-ha-inmemory-sentinel
