apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha-ondisk-sentinel
  name: redis-ha-ondisk-sentinel
  namespace: {{ .Values.odimra.namespace }}
spec:
  ports:
    - name: redis-sentinel
      port: 26379
  selector:
    app: redis-ha-ondisk-sentinel
