apiVersion: v1
kind: Service
metadata:
  name: aggregation
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: aggregation
spec:
  ports:
    - port: 45102
  selector:
    app: aggregation

