- name: Check if {{ item.path.split('/')[-1] }}.sh exists
  stat:
    path: "{{ helm_charts_path }}/{{ item.path.split('/')[-1] }}/{{ item.path.split('/')[-1] }}.sh"
  register: stat_result

- name: Invoking {{ item.path.split('/')[-1] }}.sh for install operation
  command: "/bin/bash {{ helm_charts_path }}/{{ item.path.split('/')[-1] }}/{{ item.path.split('/')[-1] }}.sh install"
  when: stat_result.stat.exists and stat_result.stat.isreg
