// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: aggregator.proto

package aggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Aggregator service

type AggregatorService interface {
	GetAggregationService(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	Reset(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	SetDefaultBootOrder(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	RediscoverSystemInventory(ctx context.Context, in *RediscoverSystemInventoryRequest, opts ...client.CallOption) (*RediscoverSystemInventoryResponse, error)
	UpdateSystemState(ctx context.Context, in *UpdateSystemStateRequest, opts ...client.CallOption) (*UpdateSystemStateResponse, error)
	AddAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetAllAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	UpdateAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	DeleteAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	CreateAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetAllAggregates(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	DeleteAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	AddElementsToAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	RemoveElementsFromAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	ResetElementsOfAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	SetDefaultBootOrderElementsOfAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetAllConnectionMethods(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	GetConnectionMethod(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error)
	SendStartUpData(ctx context.Context, in *SendStartUpDataRequest, opts ...client.CallOption) (*SendStartUpDataResponse, error)
}

type aggregatorService struct {
	c    client.Client
	name string
}

func NewAggregatorService(name string, c client.Client) AggregatorService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "aggregator"
	}
	return &aggregatorService{
		c:    c,
		name: name,
	}
}

func (c *aggregatorService) GetAggregationService(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAggregationService", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) Reset(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.Reset", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) SetDefaultBootOrder(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.SetDefaultBootOrder", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) RediscoverSystemInventory(ctx context.Context, in *RediscoverSystemInventoryRequest, opts ...client.CallOption) (*RediscoverSystemInventoryResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.RediscoverSystemInventory", in)
	out := new(RediscoverSystemInventoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) UpdateSystemState(ctx context.Context, in *UpdateSystemStateRequest, opts ...client.CallOption) (*UpdateSystemStateResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.UpdateSystemState", in)
	out := new(UpdateSystemStateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) AddAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.AddAggregationSource", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetAllAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAllAggregationSource", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAggregationSource", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) UpdateAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.UpdateAggregationSource", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) DeleteAggregationSource(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.DeleteAggregationSource", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) CreateAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.CreateAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetAllAggregates(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAllAggregates", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) DeleteAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.DeleteAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) AddElementsToAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.AddElementsToAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) RemoveElementsFromAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.RemoveElementsFromAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) ResetElementsOfAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.ResetElementsOfAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) SetDefaultBootOrderElementsOfAggregate(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.SetDefaultBootOrderElementsOfAggregate", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetAllConnectionMethods(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetAllConnectionMethods", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) GetConnectionMethod(ctx context.Context, in *AggregatorRequest, opts ...client.CallOption) (*AggregatorResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.GetConnectionMethod", in)
	out := new(AggregatorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorService) SendStartUpData(ctx context.Context, in *SendStartUpDataRequest, opts ...client.CallOption) (*SendStartUpDataResponse, error) {
	req := c.c.NewRequest(c.name, "Aggregator.SendStartUpData", in)
	out := new(SendStartUpDataResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Aggregator service

type AggregatorHandler interface {
	GetAggregationService(context.Context, *AggregatorRequest, *AggregatorResponse) error
	Reset(context.Context, *AggregatorRequest, *AggregatorResponse) error
	SetDefaultBootOrder(context.Context, *AggregatorRequest, *AggregatorResponse) error
	RediscoverSystemInventory(context.Context, *RediscoverSystemInventoryRequest, *RediscoverSystemInventoryResponse) error
	UpdateSystemState(context.Context, *UpdateSystemStateRequest, *UpdateSystemStateResponse) error
	AddAggregationSource(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetAllAggregationSource(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetAggregationSource(context.Context, *AggregatorRequest, *AggregatorResponse) error
	UpdateAggregationSource(context.Context, *AggregatorRequest, *AggregatorResponse) error
	DeleteAggregationSource(context.Context, *AggregatorRequest, *AggregatorResponse) error
	CreateAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetAllAggregates(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	DeleteAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	AddElementsToAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	RemoveElementsFromAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	ResetElementsOfAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	SetDefaultBootOrderElementsOfAggregate(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetAllConnectionMethods(context.Context, *AggregatorRequest, *AggregatorResponse) error
	GetConnectionMethod(context.Context, *AggregatorRequest, *AggregatorResponse) error
	SendStartUpData(context.Context, *SendStartUpDataRequest, *SendStartUpDataResponse) error
}

func RegisterAggregatorHandler(s server.Server, hdlr AggregatorHandler, opts ...server.HandlerOption) error {
	type aggregator interface {
		GetAggregationService(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		Reset(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		SetDefaultBootOrder(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		RediscoverSystemInventory(ctx context.Context, in *RediscoverSystemInventoryRequest, out *RediscoverSystemInventoryResponse) error
		UpdateSystemState(ctx context.Context, in *UpdateSystemStateRequest, out *UpdateSystemStateResponse) error
		AddAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetAllAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		UpdateAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		DeleteAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		CreateAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetAllAggregates(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		DeleteAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		AddElementsToAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		RemoveElementsFromAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		ResetElementsOfAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		SetDefaultBootOrderElementsOfAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetAllConnectionMethods(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		GetConnectionMethod(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error
		SendStartUpData(ctx context.Context, in *SendStartUpDataRequest, out *SendStartUpDataResponse) error
	}
	type Aggregator struct {
		aggregator
	}
	h := &aggregatorHandler{hdlr}
	return s.Handle(s.NewHandler(&Aggregator{h}, opts...))
}

type aggregatorHandler struct {
	AggregatorHandler
}

func (h *aggregatorHandler) GetAggregationService(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAggregationService(ctx, in, out)
}

func (h *aggregatorHandler) Reset(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.Reset(ctx, in, out)
}

func (h *aggregatorHandler) SetDefaultBootOrder(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.SetDefaultBootOrder(ctx, in, out)
}

func (h *aggregatorHandler) RediscoverSystemInventory(ctx context.Context, in *RediscoverSystemInventoryRequest, out *RediscoverSystemInventoryResponse) error {
	return h.AggregatorHandler.RediscoverSystemInventory(ctx, in, out)
}

func (h *aggregatorHandler) UpdateSystemState(ctx context.Context, in *UpdateSystemStateRequest, out *UpdateSystemStateResponse) error {
	return h.AggregatorHandler.UpdateSystemState(ctx, in, out)
}

func (h *aggregatorHandler) AddAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.AddAggregationSource(ctx, in, out)
}

func (h *aggregatorHandler) GetAllAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAllAggregationSource(ctx, in, out)
}

func (h *aggregatorHandler) GetAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAggregationSource(ctx, in, out)
}

func (h *aggregatorHandler) UpdateAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.UpdateAggregationSource(ctx, in, out)
}

func (h *aggregatorHandler) DeleteAggregationSource(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.DeleteAggregationSource(ctx, in, out)
}

func (h *aggregatorHandler) CreateAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.CreateAggregate(ctx, in, out)
}

func (h *aggregatorHandler) GetAllAggregates(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAllAggregates(ctx, in, out)
}

func (h *aggregatorHandler) GetAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAggregate(ctx, in, out)
}

func (h *aggregatorHandler) DeleteAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.DeleteAggregate(ctx, in, out)
}

func (h *aggregatorHandler) AddElementsToAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.AddElementsToAggregate(ctx, in, out)
}

func (h *aggregatorHandler) RemoveElementsFromAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.RemoveElementsFromAggregate(ctx, in, out)
}

func (h *aggregatorHandler) ResetElementsOfAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.ResetElementsOfAggregate(ctx, in, out)
}

func (h *aggregatorHandler) SetDefaultBootOrderElementsOfAggregate(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.SetDefaultBootOrderElementsOfAggregate(ctx, in, out)
}

func (h *aggregatorHandler) GetAllConnectionMethods(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetAllConnectionMethods(ctx, in, out)
}

func (h *aggregatorHandler) GetConnectionMethod(ctx context.Context, in *AggregatorRequest, out *AggregatorResponse) error {
	return h.AggregatorHandler.GetConnectionMethod(ctx, in, out)
}

func (h *aggregatorHandler) SendStartUpData(ctx context.Context, in *SendStartUpDataRequest, out *SendStartUpDataResponse) error {
	return h.AggregatorHandler.SendStartUpData(ctx, in, out)
}
