apiVersion: v1
kind: Service
metadata:
  name: account-session
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: account-session
spec:
  ports:
    - port: 45101
  selector:
    app: account-session

