---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: kafka
    deployment: odim-ra
spec:
  selector:
    app: kafka
    parentdeployment: odim-ra
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ext
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: kafka
    deployment: odim-ra
spec:
  selector:
    app: kafka
    parentdeployment: odim-ra
  ports:
    - name: kafka-ext
      port: 30092
      nodePort: {{ .Values.odimra.kafkaNodePort }}
      protocol: TCP
  type: NodePort
---
