---
- name: Include user defined configurations
  include_vars: "{{ helm_config_file }}"

- name: Get the current user
  local_action: command whoami
  become: false
  register: get_user

- name: Set current_user fact
  set_fact:
    current_user: "{{ get_user.stdout }}"

- name: Check if ODIMRA image path exists
  stat:
    path: "{{ odimraImagePath }}"
  register: odimra_file_details
  delegate_to: localhost
  when: odimraImagePath is defined

- name: Copy ODIMRA Images
  copy:
    src: "{{ item }}"
    dest: "{{ docker_images_path }}"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0640
  loop: "{{ files }}"
  vars:
    files:
      - "{{ odimraImagePath }}/"
  when: odimraImagePath is defined and odimra_file_details.stat.exists and odimra_file_details.stat.isdir == true and docker_image_name in item

- name: Load ODIMRA Images
  command: "{{ docker_bin_path }} load -i {{ docker_images_path }}/{{ docker_image_name}}.tar"
  when: odimraImagePath is defined and odimra_file_details.stat.exists and odimra_file_details.stat.isdir == true

-

