apiVersion: v1
kind: Service
metadata:
  name: composition-service
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: composition-service
spec:
  ports:
    - port: 45112
  selector:
    app: composition-service
