---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: etcd
    deployment: odim-ra
spec:
  type: ClusterIP
  selector:
    app: etcd
    parentdeployment: odim-ra
  ports:
    - name: etcd-server
      port: 2379
    - name: etcd-quorum
      port: 2380
