// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: update.proto

package update

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Update service

type UpdateService interface {
	GetUpdateService(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
}

type updateService struct {
	c    client.Client
	name string
}

func NewUpdateService(name string, c client.Client) UpdateService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "update"
	}
	return &updateService{
		c:    c,
		name: name,
	}
}

func (c *updateService) GetUpdateService(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Update.GetUpdateService", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Update service

type UpdateHandler interface {
	GetUpdateService(context.Context, *UpdateRequest, *UpdateResponse) error
}

func RegisterUpdateHandler(s server.Server, hdlr UpdateHandler, opts ...server.HandlerOption) error {
	type update interface {
		GetUpdateService(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
	}
	type Update struct {
		update
	}
	h := &updateHandler{hdlr}
	return s.Handle(s.NewHandler(&Update{h}, opts...))
}

type updateHandler struct {
	UpdateHandler
}

func (h *updateHandler) GetUpdateService(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.UpdateHandler.GetUpdateService(ctx, in, out)
}
