// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managers.proto

package managers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ManagerRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	ManagerID            string   `protobuf:"bytes,2,opt,name=managerID,proto3" json:"managerID,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	ResourceID           string   `protobuf:"bytes,4,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerRequest) Reset()         { *m = ManagerRequest{} }
func (m *ManagerRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerRequest) ProtoMessage()    {}
func (*ManagerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f5910ae72958ed, []int{0}
}

func (m *ManagerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerRequest.Unmarshal(m, b)
}
func (m *ManagerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerRequest.Marshal(b, m, deterministic)
}
func (m *ManagerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerRequest.Merge(m, src)
}
func (m *ManagerRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerRequest.Size(m)
}
func (m *ManagerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerRequest proto.InternalMessageInfo

func (m *ManagerRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ManagerRequest) GetManagerID() string {
	if m != nil {
		return m.ManagerID
	}
	return ""
}

func (m *ManagerRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ManagerRequest) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

type ManagerResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Header               map[string]string `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ManagerResponse) Reset()         { *m = ManagerResponse{} }
func (m *ManagerResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerResponse) ProtoMessage()    {}
func (*ManagerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f5910ae72958ed, []int{1}
}

func (m *ManagerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerResponse.Unmarshal(m, b)
}
func (m *ManagerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerResponse.Marshal(b, m, deterministic)
}
func (m *ManagerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerResponse.Merge(m, src)
}
func (m *ManagerResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerResponse.Size(m)
}
func (m *ManagerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerResponse proto.InternalMessageInfo

func (m *ManagerResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ManagerResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *ManagerResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ManagerResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ManagerRequest)(nil), "ManagerRequest")
	proto.RegisterType((*ManagerResponse)(nil), "ManagerResponse")
	proto.RegisterMapType((map[string]string)(nil), "ManagerResponse.HeaderEntry")
}

func init() { proto.RegisterFile("managers.proto", fileDescriptor_49f5910ae72958ed) }

var fileDescriptor_49f5910ae72958ed = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xf2, 0x2f, 0x2f, 0x03, 0x02, 0x19, 0x35, 0x69, 0x08, 0x31, 0xa4, 0xf1, 0xc0,
	0xa9, 0x89, 0xe8, 0x41, 0x89, 0x37, 0x30, 0x4a, 0x22, 0x97, 0x8d, 0x7e, 0x80, 0x05, 0x26, 0x48,
	0xc0, 0x5d, 0xdc, 0xd9, 0x9a, 0x70, 0xf7, 0x3b, 0xf9, 0x65, 0xfc, 0x30, 0xa6, 0xcb, 0x22, 0x85,
	0x13, 0xb7, 0x99, 0xdf, 0xcc, 0xd3, 0xe7, 0xe9, 0xb4, 0x50, 0x7b, 0x97, 0x4a, 0xce, 0xc8, 0x70,
	0xbc, 0x32, 0xda, 0xea, 0xe8, 0x2b, 0x80, 0xda, 0x68, 0x83, 0x04, 0x7d, 0x24, 0xc4, 0x16, 0x23,
	0xa8, 0x32, 0x31, 0xcf, 0xb5, 0x7a, 0xd1, 0x0b, 0x52, 0x61, 0xd0, 0x0e, 0x3a, 0x65, 0xb1, 0xc7,
	0xb0, 0x05, 0x65, 0xff, 0xa0, 0xe1, 0x20, 0xcc, 0xb9, 0x85, 0x1d, 0xc0, 0x06, 0xe4, 0x5f, 0xc5,
	0x73, 0x98, 0x77, 0x3c, 0x2d, 0xf1, 0x02, 0xc0, 0x10, 0xeb, 0xc4, 0x4c, 0x68, 0x38, 0x08, 0x0b,
	0x6e, 0x90, 0x21, 0xd1, 0x4f, 0x00, 0xf5, 0xbf, 0x18, 0xbc, 0xd2, 0x8a, 0x29, 0xd5, 0xb0, 0x95,
	0x36, 0xe1, 0xbe, 0x9e, 0x92, 0x4b, 0x51, 0x14, 0x19, 0x82, 0x97, 0x70, 0xb2, 0xe9, 0x46, 0xc4,
	0x2c, 0x67, 0xe4, 0x73, 0xec, 0x43, 0x44, 0x28, 0x8c, 0xf5, 0x74, 0xed, 0x3c, 0xab, 0xc2, 0xd5,
	0x78, 0x03, 0xa5, 0x37, 0x92, 0x53, 0x32, 0x61, 0xb1, 0x9d, 0xef, 0x54, 0xba, 0xad, 0xf8, 0xc0,
	0x3b, 0x7e, 0x72, 0xe3, 0x07, 0x65, 0xcd, 0x5a, 0xf8, 0xdd, 0xe6, 0x1d, 0x54, 0x32, 0x38, 0x7d,
	0xc9, 0x05, 0xad, 0xfd, 0x75, 0xd2, 0x12, 0xcf, 0xa0, 0xf8, 0x29, 0x97, 0xc9, 0x36, 0xc8, 0xa6,
	0xe9, 0xe5, 0x6e, 0x83, 0xee, 0x77, 0x00, 0xff, 0xbd, 0x05, 0xe3, 0x3d, 0x9c, 0x3f, 0x92, 0xdd,
	0xb6, 0x7d, 0xbd, 0x5c, 0xd2, 0xc4, 0xce, 0xb5, 0xc2, 0x7a, 0xbc, 0xff, 0x25, 0x9a, 0x8d, 0xc3,
	0x5c, 0xd1, 0x3f, 0xbc, 0x02, 0xd8, 0xa9, 0x8f, 0x93, 0xf4, 0xe0, 0x34, 0x63, 0x28, 0xfc, 0xd5,
	0x8f, 0xd2, 0x8e, 0x4b, 0xee, 0x37, 0xb9, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xe1, 0x96,
	0xea, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagersClient is the client API for Managers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagersClient interface {
	GetManagersCollection(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error)
	GetManager(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error)
	GetManagersResource(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error)
}

type managersClient struct {
	cc *grpc.ClientConn
}

func NewManagersClient(cc *grpc.ClientConn) ManagersClient {
	return &managersClient{cc}
}

func (c *managersClient) GetManagersCollection(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error) {
	out := new(ManagerResponse)
	err := c.cc.Invoke(ctx, "/Managers/GetManagersCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managersClient) GetManager(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error) {
	out := new(ManagerResponse)
	err := c.cc.Invoke(ctx, "/Managers/GetManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managersClient) GetManagersResource(ctx context.Context, in *ManagerRequest, opts ...grpc.CallOption) (*ManagerResponse, error) {
	out := new(ManagerResponse)
	err := c.cc.Invoke(ctx, "/Managers/GetManagersResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagersServer is the server API for Managers service.
type ManagersServer interface {
	GetManagersCollection(context.Context, *ManagerRequest) (*ManagerResponse, error)
	GetManager(context.Context, *ManagerRequest) (*ManagerResponse, error)
	GetManagersResource(context.Context, *ManagerRequest) (*ManagerResponse, error)
}

// UnimplementedManagersServer can be embedded to have forward compatible implementations.
type UnimplementedManagersServer struct {
}

func (*UnimplementedManagersServer) GetManagersCollection(ctx context.Context, req *ManagerRequest) (*ManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagersCollection not implemented")
}
func (*UnimplementedManagersServer) GetManager(ctx context.Context, req *ManagerRequest) (*ManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManager not implemented")
}
func (*UnimplementedManagersServer) GetManagersResource(ctx context.Context, req *ManagerRequest) (*ManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagersResource not implemented")
}

func RegisterManagersServer(s *grpc.Server, srv ManagersServer) {
	s.RegisterService(&_Managers_serviceDesc, srv)
}

func _Managers_GetManagersCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagersServer).GetManagersCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Managers/GetManagersCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagersServer).GetManagersCollection(ctx, req.(*ManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Managers_GetManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagersServer).GetManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Managers/GetManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagersServer).GetManager(ctx, req.(*ManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Managers_GetManagersResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagersServer).GetManagersResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Managers/GetManagersResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagersServer).GetManagersResource(ctx, req.(*ManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Managers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Managers",
	HandlerType: (*ManagersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManagersCollection",
			Handler:    _Managers_GetManagersCollection_Handler,
		},
		{
			MethodName: "GetManager",
			Handler:    _Managers_GetManager_Handler,
		},
		{
			MethodName: "GetManagersResource",
			Handler:    _Managers_GetManagersResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managers.proto",
}
