---
apiVersion: v1
kind: Secret
metadata:
  name: odimra-secret
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: odimra-secret
type: Opaque
data:
  rootCAcrt: {{ .Values.odimra.rootCACert | b64enc }}
  odimra_servercrt: {{ .Values.odimra.odimraServerCert | b64enc }}
  odimra_serverkey: {{ .Values.odimra.odimraServerKey | b64enc }}
  odimra_rsapublic: {{ .Values.odimra.odimraRSAPublicKey | b64enc }}
  odimra_rsaprivate: {{ .Values.odimra.odimraRSAPrivateKey | b64enc }}
  odimra_kafka_clientcrt: {{ .Values.odimra.odimraKafkaClientCert | b64enc }}
  odimra_kafka_clientkey: {{ .Values.odimra.odimraKafkaClientKey | b64enc }}
  odimra_etcd_servercrt: {{ .Values.odimra.odimraEtcdServerCert | b64enc }}
  odimra_etcd_serverkey: {{ .Values.odimra.odimraEtcdServerKey | b64enc }}
