// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fabrics/fabrics.proto

package fabrics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FabricRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,4,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FabricRequest) Reset()         { *m = FabricRequest{} }
func (m *FabricRequest) String() string { return proto.CompactTextString(m) }
func (*FabricRequest) ProtoMessage()    {}
func (*FabricRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dadab98607954ea, []int{0}
}

func (m *FabricRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricRequest.Unmarshal(m, b)
}
func (m *FabricRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricRequest.Marshal(b, m, deterministic)
}
func (m *FabricRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricRequest.Merge(m, src)
}
func (m *FabricRequest) XXX_Size() int {
	return xxx_messageInfo_FabricRequest.Size(m)
}
func (m *FabricRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FabricRequest proto.InternalMessageInfo

func (m *FabricRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *FabricRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *FabricRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *FabricRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type AddFabricRequest struct {
	OriginResource       string   `protobuf:"bytes,1,opt,name=originResource,proto3" json:"originResource,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFabricRequest) Reset()         { *m = AddFabricRequest{} }
func (m *AddFabricRequest) String() string { return proto.CompactTextString(m) }
func (*AddFabricRequest) ProtoMessage()    {}
func (*AddFabricRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dadab98607954ea, []int{1}
}

func (m *AddFabricRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFabricRequest.Unmarshal(m, b)
}
func (m *AddFabricRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFabricRequest.Marshal(b, m, deterministic)
}
func (m *AddFabricRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFabricRequest.Merge(m, src)
}
func (m *AddFabricRequest) XXX_Size() int {
	return xxx_messageInfo_AddFabricRequest.Size(m)
}
func (m *AddFabricRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFabricRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFabricRequest proto.InternalMessageInfo

func (m *AddFabricRequest) GetOriginResource() string {
	if m != nil {
		return m.OriginResource
	}
	return ""
}

func (m *AddFabricRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type FabricResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FabricResponse) Reset()         { *m = FabricResponse{} }
func (m *FabricResponse) String() string { return proto.CompactTextString(m) }
func (*FabricResponse) ProtoMessage()    {}
func (*FabricResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dadab98607954ea, []int{2}
}

func (m *FabricResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricResponse.Unmarshal(m, b)
}
func (m *FabricResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricResponse.Marshal(b, m, deterministic)
}
func (m *FabricResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricResponse.Merge(m, src)
}
func (m *FabricResponse) XXX_Size() int {
	return xxx_messageInfo_FabricResponse.Size(m)
}
func (m *FabricResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FabricResponse proto.InternalMessageInfo

func (m *FabricResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FabricResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *FabricResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FabricResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*FabricRequest)(nil), "FabricRequest")
	proto.RegisterType((*AddFabricRequest)(nil), "AddFabricRequest")
	proto.RegisterType((*FabricResponse)(nil), "FabricResponse")
	proto.RegisterMapType((map[string]string)(nil), "FabricResponse.HeaderEntry")
}

func init() { proto.RegisterFile("fabrics/fabrics.proto", fileDescriptor_4dadab98607954ea) }

var fileDescriptor_4dadab98607954ea = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0xf2, 0x50,
	0x10, 0xfd, 0x4a, 0xf9, 0x09, 0xc3, 0xcf, 0x07, 0x13, 0x34, 0x0d, 0x26, 0xa6, 0x69, 0x8c, 0x61,
	0x55, 0x23, 0x24, 0x46, 0xdc, 0xf9, 0xef, 0x42, 0x36, 0x0d, 0x3c, 0x40, 0xe1, 0x8e, 0xd0, 0x40,
	0x7a, 0xb1, 0x73, 0x6b, 0xc2, 0xca, 0xf7, 0xf4, 0x11, 0x7c, 0x0a, 0x43, 0x7b, 0x41, 0x4a, 0xe2,
	0x42, 0x57, 0x9d, 0x73, 0xee, 0xed, 0x39, 0x67, 0x66, 0x2e, 0x1c, 0xbc, 0xf8, 0xe3, 0x28, 0x98,
	0xf0, 0x99, 0xfe, 0xba, 0xcb, 0x48, 0x2a, 0xe9, 0xbc, 0x43, 0xed, 0x21, 0x21, 0x3c, 0x7a, 0x8d,
	0x89, 0x15, 0x3a, 0x50, 0x65, 0x62, 0x0e, 0x64, 0x38, 0x94, 0x73, 0x0a, 0x2d, 0xc3, 0x36, 0x3a,
	0x65, 0x2f, 0xc3, 0x61, 0x03, 0xcc, 0x91, 0xf7, 0x6c, 0xe5, 0x92, 0xa3, 0x75, 0x89, 0x87, 0x50,
	0x1c, 0x90, 0x9a, 0x49, 0x61, 0x99, 0x09, 0xa9, 0x11, 0xda, 0x50, 0xd1, 0xc2, 0x37, 0x52, 0xac,
	0xac, 0xbc, 0x6d, 0x74, 0xaa, 0xde, 0x2e, 0xe5, 0x0c, 0xa1, 0x71, 0x2d, 0x44, 0x36, 0xc3, 0x29,
	0xd4, 0x65, 0x14, 0x4c, 0x83, 0xd0, 0x23, 0x96, 0x71, 0x34, 0x21, 0x9d, 0x62, 0x8f, 0x45, 0x0b,
	0x4a, 0xbe, 0x10, 0x11, 0x31, 0xeb, 0x2c, 0x1b, 0xe8, 0x7c, 0x18, 0x50, 0xdf, 0x68, 0xf2, 0x52,
	0x86, 0x4c, 0x78, 0x0c, 0xc0, 0xca, 0x57, 0x31, 0xdf, 0x4a, 0x91, 0x0a, 0x16, 0xbc, 0x1d, 0x06,
	0x4f, 0xa0, 0x96, 0xa2, 0x01, 0x31, 0xfb, 0x53, 0xd2, 0x92, 0x59, 0x12, 0x7b, 0x50, 0x9c, 0x91,
	0x2f, 0x28, 0xb2, 0x4c, 0xdb, 0xec, 0x54, 0xba, 0x47, 0x6e, 0xd6, 0xc6, 0x7d, 0x4a, 0x4e, 0xef,
	0x43, 0x15, 0xad, 0x3c, 0x7d, 0x15, 0x11, 0xf2, 0xe3, 0xef, 0xf6, 0x93, 0xba, 0xdd, 0x87, 0xca,
	0xce, 0xd5, 0xf5, 0x48, 0xe7, 0xb4, 0xd2, 0x7d, 0xae, 0x4b, 0x6c, 0x41, 0xe1, 0xcd, 0x5f, 0xc4,
	0x9b, 0x1c, 0x29, 0xb8, 0xca, 0x5d, 0x1a, 0xdd, 0x4f, 0x03, 0x4a, 0xa9, 0x2b, 0xe3, 0x05, 0x34,
	0x1f, 0x49, 0x6d, 0x33, 0xa4, 0x73, 0xa9, 0xbb, 0x99, 0x79, 0xb6, 0xff, 0xef, 0x85, 0x74, 0xfe,
	0x61, 0x1f, 0x5a, 0xa3, 0xa5, 0xf0, 0x15, 0xfd, 0xfe, 0xd7, 0x73, 0x28, 0x6f, 0x37, 0x86, 0x4d,
	0x77, 0x7f, 0x7b, 0x3f, 0xb8, 0xdd, 0xd1, 0x82, 0xfe, 0xe0, 0x36, 0x2e, 0x26, 0xef, 0xb4, 0xf7,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x1f, 0x3d, 0x9e, 0xc0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FabricsClient is the client API for Fabrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FabricsClient interface {
	GetFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error)
	UpdateFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error)
	AddFabric(ctx context.Context, in *AddFabricRequest, opts ...grpc.CallOption) (*FabricResponse, error)
	DeleteFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error)
}

type fabricsClient struct {
	cc *grpc.ClientConn
}

func NewFabricsClient(cc *grpc.ClientConn) FabricsClient {
	return &fabricsClient{cc}
}

func (c *fabricsClient) GetFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error) {
	out := new(FabricResponse)
	err := c.cc.Invoke(ctx, "/Fabrics/GetFabricResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricsClient) UpdateFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error) {
	out := new(FabricResponse)
	err := c.cc.Invoke(ctx, "/Fabrics/UpdateFabricResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricsClient) AddFabric(ctx context.Context, in *AddFabricRequest, opts ...grpc.CallOption) (*FabricResponse, error) {
	out := new(FabricResponse)
	err := c.cc.Invoke(ctx, "/Fabrics/AddFabric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricsClient) DeleteFabricResource(ctx context.Context, in *FabricRequest, opts ...grpc.CallOption) (*FabricResponse, error) {
	out := new(FabricResponse)
	err := c.cc.Invoke(ctx, "/Fabrics/DeleteFabricResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricsServer is the server API for Fabrics service.
type FabricsServer interface {
	GetFabricResource(context.Context, *FabricRequest) (*FabricResponse, error)
	UpdateFabricResource(context.Context, *FabricRequest) (*FabricResponse, error)
	AddFabric(context.Context, *AddFabricRequest) (*FabricResponse, error)
	DeleteFabricResource(context.Context, *FabricRequest) (*FabricResponse, error)
}

// UnimplementedFabricsServer can be embedded to have forward compatible implementations.
type UnimplementedFabricsServer struct {
}

func (*UnimplementedFabricsServer) GetFabricResource(ctx context.Context, req *FabricRequest) (*FabricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFabricResource not implemented")
}
func (*UnimplementedFabricsServer) UpdateFabricResource(ctx context.Context, req *FabricRequest) (*FabricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFabricResource not implemented")
}
func (*UnimplementedFabricsServer) AddFabric(ctx context.Context, req *AddFabricRequest) (*FabricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFabric not implemented")
}
func (*UnimplementedFabricsServer) DeleteFabricResource(ctx context.Context, req *FabricRequest) (*FabricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFabricResource not implemented")
}

func RegisterFabricsServer(s *grpc.Server, srv FabricsServer) {
	s.RegisterService(&_Fabrics_serviceDesc, srv)
}

func _Fabrics_GetFabricResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricsServer).GetFabricResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fabrics/GetFabricResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricsServer).GetFabricResource(ctx, req.(*FabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabrics_UpdateFabricResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricsServer).UpdateFabricResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fabrics/UpdateFabricResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricsServer).UpdateFabricResource(ctx, req.(*FabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabrics_AddFabric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricsServer).AddFabric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fabrics/AddFabric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricsServer).AddFabric(ctx, req.(*AddFabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabrics_DeleteFabricResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricsServer).DeleteFabricResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fabrics/DeleteFabricResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricsServer).DeleteFabricResource(ctx, req.(*FabricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fabrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Fabrics",
	HandlerType: (*FabricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFabricResource",
			Handler:    _Fabrics_GetFabricResource_Handler,
		},
		{
			MethodName: "UpdateFabricResource",
			Handler:    _Fabrics_UpdateFabricResource_Handler,
		},
		{
			MethodName: "AddFabric",
			Handler:    _Fabrics_AddFabric_Handler,
		},
		{
			MethodName: "DeleteFabricResource",
			Handler:    _Fabrics_DeleteFabricResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fabrics/fabrics.proto",
}
