apiVersion: v1
kind: ConfigMap
metadata:
  name: csplugin-config
  namespace: {{ .Values.odimra.namespace }}
data:
  config.json: |
    {
        "Host": "{{ .Values.csplugin.host }}",
        "Port": "45100",
        "UserName": "{{ .Values.csplugin.username }}",
        "Password": "{{ .Values.csplugin.password }}",
        "RootServiceUUID": "{{ .Values.csplugin.csPluginRootServiceUUID }}",
        "OdimURL": "https://api:45000",
        "OdimUserName": "{{ .Values.csplugin.odimUsername }}",
        "OdimPassword": "{{ .Values.csplugin.odimPassword }}",
        "FirmwareVersion": "v1.0.0",
        "LogLevel": "debug",
        "LogPath": "/var/log/csplugin_logs/csplugin.log",
        "RedisAddress": "redis-inmemory:6379",
        "PrivateKeyPath": "/etc/csplugin_certs/odimra_server.key",
        "CertificatePath": "/etc/csplugin_certs/odimra_server.crt",
        "RootCAPath": "/etc/csplugin_certs/rootCA.crt",
        "RSAPrivateKeyPath": "/etc/csplugin_certs/odimra_rsa.private",
        "RSAPublicKeyPath": "/etc/urplugin_certs/odimra_rsa.public"
    }
  
