---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: odim-ra
    unit: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: odim-ra
    unit: zookeeper
    parentdeployment: odim-zookeeper
  ports:
    - name: zookeeper
      port: 2181
    - name: zookeeper-leader
      port: 2888
    - name: zookeeper-follower
      port: 3888
