---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: odim-ra
    unit: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odim-ra
      unit: consul
      parentdeployment: odim-ra
  template:
    metadata:
      labels:
        app: odim-ra
        unit: consul
        parentdeployment: odim-ra
    spec:
      hostname: consul
      subdomain: consul
      securityContext:
        fsGroup: {{ .Values.odimra.groupID }}
      containers:
        - name: consul
          image: consul:{{ .Values.odimra.consulImageTag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: IS_CONSUL_CLUSTER
              value: 'false'
          ports:
            - name: consul-rpc-svc
              containerPort: 8300
            - name: consul-lan-serf
              containerPort: 8301
            - name: consul-wan-serf
              containerPort: 8302
            - name: consul-api-svc
              containerPort: 8500
            - name: consul-dns-svc
              containerPort: 8600
          volumeMounts:
            - mountPath: "/consul/data"
              name: consul-data-pv
      volumes:
        - name: consul-data-pv
          persistentVolumeClaim:
            claimName: consul-data-pvc
