---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: consul
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: odim-ra
    unit: consul
spec:
  type: ClusterIP
  selector:
    app: odim-ra
    unit: consul
    parentdeployment: odim-ra
  ports:
    - name: consul-rpc-svc
      port: 8300
    - name: consul-lan-serf
      port: 8301
    - name: consul-wan-serf
      port: 8302
    - name: consul-api-svc
      port: 8500
    - name: consul-dns-svc
      port: 8600
