apiVersion: v1
kind: ConfigMap
metadata:
  name: dellplugin-config
  namespace: {{ .Values.odimra.namespace }}
data: 
  config.json: |
    {
    	"RootServiceUUID": {{ .Values.dellplugin.dellPluginRootServiceUUID | quote }},
    	"PluginConf": {
    		"ID": "DELL",
    		"Host": {{ .Values.dellplugin.host | quote }},
    		"Port": "45005",
    		"UserName": {{ .Values.dellplugin.username | quote }},
    		"Password": {{ .Values.dellplugin.password | quote }}
    	},
    	"EventConf": {
    		"DestinationURI": "/redfishEventListener",
    		"ListenerHost": {{ .Values.dellplugin.eventHost | quote }},
    		"ListenerPort": "45006"
    	},
    	"KeyCertConf": {
    		"RootCACertificatePath": "/etc/odimra_certs/rootCA.crt",
    		"PrivateKeyPath": "/etc/odimra_certs/odimra_server.key",
    		"CertificatePath": "/etc/odimra_certs/odimra_server.crt"
    	},
        "DBConf": {
                   "Protocol": "tcp",
                   {{ if eq .Values.odimra.haDeploymentEnabled false }}
                   "InMemoryHost": "redis-inmemory",
                   "OnDiskHost": "redis-ondisk",
                   "InMemoryMasterSet": "mymaster",
                   "OnDiskMasterSet": "mymaster",
                   {{ else }}
                   "InMemoryHost": "redis-ha-inmemory",
                   "OnDiskHost": "redis-ha-ondisk",
                   "InMemoryMasterSet": "primaryset",
                   "OnDiskMasterSet": "primaryset",
                   {{ end }}
                   "InMemoryPort": "6379",
                   "OnDiskPort": "6379",
                   "MaxIdleConns": 200,
                   "MaxActiveConns": 200,
                   "RedisHAEnabled": {{ .Values.odimra.haDeploymentEnabled }},
                   "InMemorySentinelPort": "26379",
                   "OnDiskSentinelPort": "26379"
        },
    	"TLSConf" : {
    		"MinVersion": "TLS_1.2",
    		"MaxVersion": "TLS_1.2",
    		"VerifyPeer": true,
    		"PreferredCipherSuites": [
                        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                        "TLS_RSA_WITH_AES_128_GCM_SHA256",
                        "TLS_RSA_WITH_AES_256_GCM_SHA384"
    		]
    	},
    	"FirmwareVersion": "v1.0.0",
    	"SessionTimeoutInMinutes": 30,
    	"LoadBalancerConf": {
    		"LBHost": {{ .Values.dellplugin.lbHost | quote }},
    		"LBPort": {{ .Values.dellplugin.lbPort | quote }}
    	},
    	"MessageBusConf": {
    		"MessageQueueConfigFilePath": "/etc/dellplugin_config/platformconfig.toml",
    		"MessageBusType": "Kafka",
    		"MessageBusQueue": ["REDFISH-EVENTS-TOPIC"]
    	},
    	"URLTranslation": {
    		"NorthBoundURL": {
    			"redfish": "ODIM"
    		},
    		"SouthBoundURL": {
    			"ODIM": "redfish"
    		}
    	}
    }
