---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dellplugin-log
  namespace: {{ .Values.odimra.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.odimra.namespace }}
    name: dellplugin-log-claim
  hostPath:
    path: {{ .Values.dellplugin.logPath }}
