apiVersion: v1
kind: Service
metadata:
  name: dellplugin
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: dellplugin
spec:
  ports:
    - port: 45005
  selector:
    app: dellplugin
---
apiVersion: v1
kind: Service
metadata:
  name: dellplugin-events
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: dellplugin
spec:
  type: NodePort
  ports:
  - port: 45006
    nodePort: {{ .Values.dellplugin.eventListenerNodePort }}
    protocol: TCP
  {{ if eq .Values.odimra.haDeploymentEnabled false }}
  externalTrafficPolicy: Local
  {{ end }}
  selector:
    app: dellplugin
