apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.odimra.namespace }}
  annotations:
    secret.reloader.stakater.com/reload: "odimra-secret"
spec:
  replicas: {{ .Values.ReplicaCount | default 1 }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        {{- if eq .Values.odimra.deploymentType "K8S" }}
        kubernetes.labels.hpe_com_space: {{ .Values.odimra.namespace }}
        kubernetes.labels.hpe_com_stack: api-gateway
        kubernetes.labels.hpe_com_component: api
        kubernetes.labels.hpe_com_app: api
        {{- else if .Values.odimra.deploymentType "RHOCP"}}
        kubernetes.flat_labels.hpe_com/space: {{ .Values.odimra.namespace }} 
        kubernetes.flat_labels.hpe_com/stack: api-gateway
        kubernetes.flat_labels.hpe_com/component: api
        kubernetes.flat_labels.hpe_com/app : api
        {{- end }}
      name: dapi-envars-fieldref
      name: dapi-envars-fieldref
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 3
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: api
      hostname: api
      volumes:
        - name: odimra-config-vol
          projected:
            sources:
            - configMap:
                name: odimra-config
            - configMap:
                name: odimra-platformconfig
        - name: configure-hosts
          configMap:
            name: configure-hosts
            items:
            - key: hosts
              path: host.append
              mode: 0644
        - name: odimra-secret
          secret:
            secretName: odimra-secret
            items: 
            - key: rootCAcrt
              path: rootCA.crt
              mode: 0444
            - key: odimra_servercrt
              path: odimra_server.crt
              mode: 0444
            - key: odimra_serverkey
              path: odimra_server.key
              mode: 0444
            - key: odimra_rsapublic
              path: odimra_rsa.public
              mode: 0444
            - key: odimra_rsaprivate
              path: odimra_rsa.private
              mode: 0444
            - key: redis_inmemory_password
              path: redis_inmemory_password
              mode: 0444
            - key: redis_ondisk_password
              path: redis_ondisk_password
              mode: 0444
            {{- if eq .Values.odimra.messageBusType "Kafka" }}
            - key: odimra_kafka_clientcrt
              path: odimra_kafka_client.crt
              mode: 0444
            - key: odimra_kafka_clientkey
              path: odimra_kafka_client.key
              mode: 0444
            {{- end }}
        - name: odimra-log
          persistentVolumeClaim:
            claimName: odimra-log-claim
      securityContext:
        fsGroup: {{ .Values.odimra.groupID }}
        runAsUser: {{ .Values.odimra.userID }}
      containers:
        - name: api
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: HA_ENABLED
              value: {{ .Values.odimra.haDeploymentEnabled | quote }}
            - name: ODIM_NAMESPACE
              value: {{ .Values.odimra.namespace | quote }}
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: {{ .Values.odimra.imageRegistryAddress| default  }}api:{{ .Values.odimra.apiImageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 45000
          volumeMounts:
            - name: odimra-config-vol
              mountPath: /etc/odimra_config
            - name: configure-hosts
              mountPath: /tmp
            - name: odimra-log
              mountPath: /var/log/odimra_logs
            - name: odimra-secret
              mountPath: /etc/odimra_certs
