- name: Check if {{ item.path.split('/')[-1] }}.sh exists
  stat:
    path: "{{ helm_charts_path }}/{{ item.path.split('/')[-1] }}/{{ item.path.split('/')[-1] }}.sh"
  register: stat_result
  ignore_errors: "{{ ignore_err }}"

- name: Invoking {{ item.path.split('/')[-1] }}.sh for uninstall operation
  command: "/bin/bash {{ helm_charts_path }}/{{ item.path.split('/')[-1] }}/{{ item.path.split('/')[-1] }}.sh uninstall"
  when: stat_result.stat.exists and stat_result.stat.isreg
  ignore_errors: "{{ ignore_err }}"
