// Code generated by protoc-gen-go. DO NOT EDIT.
// source: systems.proto

package systems

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSystemsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	RequestParam         string   `protobuf:"bytes,2,opt,name=requestParam,proto3" json:"requestParam,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	ResourceID           string   `protobuf:"bytes,4,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemsRequest) Reset()         { *m = GetSystemsRequest{} }
func (m *GetSystemsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemsRequest) ProtoMessage()    {}
func (*GetSystemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{0}
}

func (m *GetSystemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemsRequest.Unmarshal(m, b)
}
func (m *GetSystemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemsRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemsRequest.Merge(m, src)
}
func (m *GetSystemsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemsRequest.Size(m)
}
func (m *GetSystemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemsRequest proto.InternalMessageInfo

func (m *GetSystemsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *GetSystemsRequest) GetRequestParam() string {
	if m != nil {
		return m.RequestParam
	}
	return ""
}

func (m *GetSystemsRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GetSystemsRequest) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

type SystemsResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SystemsResponse) Reset()         { *m = SystemsResponse{} }
func (m *SystemsResponse) String() string { return proto.CompactTextString(m) }
func (*SystemsResponse) ProtoMessage()    {}
func (*SystemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{1}
}

func (m *SystemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsResponse.Unmarshal(m, b)
}
func (m *SystemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsResponse.Marshal(b, m, deterministic)
}
func (m *SystemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsResponse.Merge(m, src)
}
func (m *SystemsResponse) XXX_Size() int {
	return xxx_messageInfo_SystemsResponse.Size(m)
}
func (m *SystemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsResponse proto.InternalMessageInfo

func (m *SystemsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SystemsResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *SystemsResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SystemsResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ComputerSystemResetRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputerSystemResetRequest) Reset()         { *m = ComputerSystemResetRequest{} }
func (m *ComputerSystemResetRequest) String() string { return proto.CompactTextString(m) }
func (*ComputerSystemResetRequest) ProtoMessage()    {}
func (*ComputerSystemResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{2}
}

func (m *ComputerSystemResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputerSystemResetRequest.Unmarshal(m, b)
}
func (m *ComputerSystemResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputerSystemResetRequest.Marshal(b, m, deterministic)
}
func (m *ComputerSystemResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputerSystemResetRequest.Merge(m, src)
}
func (m *ComputerSystemResetRequest) XXX_Size() int {
	return xxx_messageInfo_ComputerSystemResetRequest.Size(m)
}
func (m *ComputerSystemResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputerSystemResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputerSystemResetRequest proto.InternalMessageInfo

func (m *ComputerSystemResetRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ComputerSystemResetRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *ComputerSystemResetRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type DefaultBootOrderRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultBootOrderRequest) Reset()         { *m = DefaultBootOrderRequest{} }
func (m *DefaultBootOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultBootOrderRequest) ProtoMessage()    {}
func (*DefaultBootOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{3}
}

func (m *DefaultBootOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultBootOrderRequest.Unmarshal(m, b)
}
func (m *DefaultBootOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultBootOrderRequest.Marshal(b, m, deterministic)
}
func (m *DefaultBootOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultBootOrderRequest.Merge(m, src)
}
func (m *DefaultBootOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultBootOrderRequest.Size(m)
}
func (m *DefaultBootOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultBootOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultBootOrderRequest proto.InternalMessageInfo

func (m *DefaultBootOrderRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *DefaultBootOrderRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

type BiosSettingsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiosSettingsRequest) Reset()         { *m = BiosSettingsRequest{} }
func (m *BiosSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*BiosSettingsRequest) ProtoMessage()    {}
func (*BiosSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{4}
}

func (m *BiosSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiosSettingsRequest.Unmarshal(m, b)
}
func (m *BiosSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiosSettingsRequest.Marshal(b, m, deterministic)
}
func (m *BiosSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiosSettingsRequest.Merge(m, src)
}
func (m *BiosSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_BiosSettingsRequest.Size(m)
}
func (m *BiosSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiosSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiosSettingsRequest proto.InternalMessageInfo

func (m *BiosSettingsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *BiosSettingsRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *BiosSettingsRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type BootOrderSettingsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootOrderSettingsRequest) Reset()         { *m = BootOrderSettingsRequest{} }
func (m *BootOrderSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*BootOrderSettingsRequest) ProtoMessage()    {}
func (*BootOrderSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{5}
}

func (m *BootOrderSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootOrderSettingsRequest.Unmarshal(m, b)
}
func (m *BootOrderSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootOrderSettingsRequest.Marshal(b, m, deterministic)
}
func (m *BootOrderSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootOrderSettingsRequest.Merge(m, src)
}
func (m *BootOrderSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_BootOrderSettingsRequest.Size(m)
}
func (m *BootOrderSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootOrderSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootOrderSettingsRequest proto.InternalMessageInfo

func (m *BootOrderSettingsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *BootOrderSettingsRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *BootOrderSettingsRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type CreateVolumeRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	StorageInstance      string   `protobuf:"bytes,3,opt,name=StorageInstance,proto3" json:"StorageInstance,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,4,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVolumeRequest) Reset()         { *m = CreateVolumeRequest{} }
func (m *CreateVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeRequest) ProtoMessage()    {}
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938d4cda008df6, []int{6}
}

func (m *CreateVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeRequest.Unmarshal(m, b)
}
func (m *CreateVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeRequest.Marshal(b, m, deterministic)
}
func (m *CreateVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeRequest.Merge(m, src)
}
func (m *CreateVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeRequest.Size(m)
}
func (m *CreateVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeRequest proto.InternalMessageInfo

func (m *CreateVolumeRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *CreateVolumeRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *CreateVolumeRequest) GetStorageInstance() string {
	if m != nil {
		return m.StorageInstance
	}
	return ""
}

func (m *CreateVolumeRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSystemsRequest)(nil), "GetSystemsRequest")
	proto.RegisterType((*SystemsResponse)(nil), "SystemsResponse")
	proto.RegisterMapType((map[string]string)(nil), "SystemsResponse.HeaderEntry")
	proto.RegisterType((*ComputerSystemResetRequest)(nil), "ComputerSystemResetRequest")
	proto.RegisterType((*DefaultBootOrderRequest)(nil), "DefaultBootOrderRequest")
	proto.RegisterType((*BiosSettingsRequest)(nil), "BiosSettingsRequest")
	proto.RegisterType((*BootOrderSettingsRequest)(nil), "BootOrderSettingsRequest")
	proto.RegisterType((*CreateVolumeRequest)(nil), "CreateVolumeRequest")
}

func init() { proto.RegisterFile("systems.proto", fileDescriptor_ec938d4cda008df6) }

var fileDescriptor_ec938d4cda008df6 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0x5a, 0x60, 0x9a, 0xaa, 0x65, 0x12, 0xa9, 0x26, 0x20, 0x14, 0x59, 0x1c, 0x72,
	0xf2, 0xa1, 0xf4, 0x50, 0x40, 0xea, 0x21, 0x0e, 0xd0, 0x48, 0x20, 0x90, 0x0d, 0x48, 0x1c, 0xb7,
	0xc9, 0x90, 0x46, 0x75, 0xbc, 0x61, 0x77, 0x0c, 0x8a, 0x84, 0xf8, 0x03, 0x3e, 0x82, 0xaf, 0xe1,
	0x27, 0xf8, 0x18, 0x64, 0x7b, 0x49, 0xb7, 0xae, 0x23, 0xb5, 0x52, 0xc4, 0x6d, 0xf7, 0xed, 0xbc,
	0x99, 0xb7, 0xd6, 0x7b, 0x6b, 0xd8, 0xd1, 0x0b, 0xcd, 0x34, 0xd3, 0xc1, 0x5c, 0x49, 0x96, 0xfe,
	0x4f, 0x07, 0xee, 0xbd, 0x22, 0x8e, 0x4b, 0x30, 0xa2, 0x2f, 0x19, 0x69, 0x46, 0x1f, 0x9a, 0x9a,
	0xb4, 0x9e, 0xca, 0xf4, 0xbd, 0x3c, 0xa7, 0xd4, 0x73, 0xba, 0x4e, 0xef, 0x6e, 0x74, 0x09, 0xcb,
	0x6b, 0x54, 0x59, 0xfe, 0x4e, 0x28, 0x31, 0xf3, 0x36, 0xca, 0x1a, 0x1b, 0xc3, 0x3d, 0x70, 0x3f,
	0x44, 0xaf, 0x3d, 0xb7, 0x38, 0xca, 0x97, 0xf8, 0x08, 0x40, 0x91, 0x96, 0x99, 0x1a, 0xd1, 0x70,
	0xe0, 0x35, 0x8a, 0x03, 0x0b, 0xf1, 0xff, 0x38, 0xb0, 0xbb, 0x14, 0xa3, 0xe7, 0x32, 0xd5, 0x94,
	0x73, 0x34, 0x0b, 0xce, 0x74, 0x28, 0xc7, 0x54, 0x68, 0xd9, 0x8c, 0x2c, 0x04, 0x1f, 0xc3, 0x4e,
	0xb9, 0x7b, 0x43, 0x5a, 0x8b, 0x09, 0x19, 0x29, 0x97, 0x41, 0x3c, 0x84, 0xad, 0x33, 0x12, 0x63,
	0x52, 0x9e, 0xdb, 0x75, 0x7b, 0xdb, 0x07, 0x0f, 0x83, 0xca, 0x9c, 0xe0, 0xa4, 0x38, 0x7e, 0x91,
	0xb2, 0x5a, 0x44, 0xa6, 0x16, 0x11, 0x1a, 0xa7, 0x72, 0xbc, 0x28, 0x94, 0x36, 0xa3, 0x62, 0xdd,
	0x79, 0x0a, 0xdb, 0x56, 0x69, 0x7e, 0xc9, 0x73, 0x5a, 0x98, 0x6f, 0x94, 0x2f, 0xb1, 0x0d, 0x9b,
	0x5f, 0x45, 0x92, 0xfd, 0x13, 0x52, 0x6e, 0x9e, 0x6d, 0x1c, 0x39, 0xfe, 0x0f, 0xe8, 0x84, 0x72,
	0x36, 0xcf, 0x98, 0x54, 0x39, 0x3d, 0x22, 0x4d, 0x7c, 0x93, 0xcf, 0xde, 0x81, 0x3b, 0x25, 0x73,
	0x38, 0x30, 0xed, 0x97, 0x7b, 0xec, 0xc2, 0xb6, 0x69, 0xd5, 0xcf, 0x35, 0xbb, 0x85, 0x66, 0x1b,
	0xf2, 0x3f, 0xc1, 0xfe, 0x80, 0x3e, 0x8b, 0x2c, 0xe1, 0xbe, 0x94, 0xfc, 0x56, 0x8d, 0x49, 0xad,
	0x69, 0xb8, 0xff, 0x0d, 0x5a, 0xfd, 0xa9, 0xd4, 0x31, 0x31, 0x4f, 0xd3, 0x89, 0x6d, 0xa5, 0xb8,
	0xa6, 0x6d, 0xbc, 0xbe, 0x3b, 0x7d, 0x07, 0x6f, 0x79, 0x99, 0xff, 0x3f, 0xfd, 0x97, 0x03, 0xad,
	0x50, 0x91, 0x60, 0xfa, 0x28, 0x93, 0x6c, 0x46, 0xeb, 0x9a, 0xdc, 0x83, 0xdd, 0x98, 0xa5, 0x12,
	0x13, 0x1a, 0xa6, 0x9a, 0x45, 0x3a, 0x22, 0x13, 0xa3, 0x2a, 0x5c, 0xd5, 0xd8, 0xb8, 0xa2, 0xf1,
	0xe0, 0x77, 0x03, 0x6e, 0x1b, 0xb3, 0xe3, 0x31, 0xb4, 0x2f, 0xf2, 0x1e, 0xca, 0x24, 0xa1, 0x11,
	0x4f, 0x65, 0x8a, 0x18, 0x5c, 0x79, 0x06, 0x3a, 0x7b, 0xd5, 0x88, 0xf8, 0xb7, 0xf0, 0xb9, 0xf5,
	0x5e, 0x44, 0x26, 0xb7, 0xd7, 0x26, 0x1f, 0x02, 0x5c, 0x14, 0x5e, 0x9b, 0xf5, 0x12, 0x5a, 0x35,
	0xa1, 0xc1, 0x07, 0xc1, 0xea, 0x28, 0xd5, 0xf6, 0x09, 0xa1, 0x15, 0x13, 0x57, 0xfd, 0x8f, 0x5e,
	0xb0, 0x22, 0x12, 0xb5, 0x4d, 0x8e, 0x01, 0xc3, 0x33, 0x91, 0x4e, 0xc8, 0x36, 0x3b, 0xb6, 0x83,
	0x1a, 0xef, 0xd7, 0xf2, 0x4f, 0x60, 0xdf, 0xf0, 0xab, 0x9e, 0xc5, 0xfb, 0xc1, 0x2a, 0x1f, 0xd7,
	0x76, 0x3a, 0x82, 0xa6, 0x6d, 0x3c, 0x6c, 0x07, 0x35, 0x3e, 0x5c, 0xc5, 0x1c, 0x50, 0x42, 0x37,
	0x67, 0x9e, 0x6e, 0x15, 0x7f, 0x8d, 0x27, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xaa, 0xdf,
	0xfd, 0x46, 0x06, 0x00, 0x00,
}
