// Code generated by protoc-gen-go. DO NOT EDIT.
// source: systems/systems.proto

package systems

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSystemsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	RequestParam         string   `protobuf:"bytes,2,opt,name=requestParam,proto3" json:"requestParam,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	ResourceID           string   `protobuf:"bytes,4,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemsRequest) Reset()         { *m = GetSystemsRequest{} }
func (m *GetSystemsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemsRequest) ProtoMessage()    {}
func (*GetSystemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{0}
}

func (m *GetSystemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemsRequest.Unmarshal(m, b)
}
func (m *GetSystemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemsRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemsRequest.Merge(m, src)
}
func (m *GetSystemsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemsRequest.Size(m)
}
func (m *GetSystemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemsRequest proto.InternalMessageInfo

func (m *GetSystemsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *GetSystemsRequest) GetRequestParam() string {
	if m != nil {
		return m.RequestParam
	}
	return ""
}

func (m *GetSystemsRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *GetSystemsRequest) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

type SystemsResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SystemsResponse) Reset()         { *m = SystemsResponse{} }
func (m *SystemsResponse) String() string { return proto.CompactTextString(m) }
func (*SystemsResponse) ProtoMessage()    {}
func (*SystemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{1}
}

func (m *SystemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsResponse.Unmarshal(m, b)
}
func (m *SystemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsResponse.Marshal(b, m, deterministic)
}
func (m *SystemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsResponse.Merge(m, src)
}
func (m *SystemsResponse) XXX_Size() int {
	return xxx_messageInfo_SystemsResponse.Size(m)
}
func (m *SystemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsResponse proto.InternalMessageInfo

func (m *SystemsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SystemsResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *SystemsResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SystemsResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ComputerSystemResetRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputerSystemResetRequest) Reset()         { *m = ComputerSystemResetRequest{} }
func (m *ComputerSystemResetRequest) String() string { return proto.CompactTextString(m) }
func (*ComputerSystemResetRequest) ProtoMessage()    {}
func (*ComputerSystemResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{2}
}

func (m *ComputerSystemResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputerSystemResetRequest.Unmarshal(m, b)
}
func (m *ComputerSystemResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputerSystemResetRequest.Marshal(b, m, deterministic)
}
func (m *ComputerSystemResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputerSystemResetRequest.Merge(m, src)
}
func (m *ComputerSystemResetRequest) XXX_Size() int {
	return xxx_messageInfo_ComputerSystemResetRequest.Size(m)
}
func (m *ComputerSystemResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputerSystemResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputerSystemResetRequest proto.InternalMessageInfo

func (m *ComputerSystemResetRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ComputerSystemResetRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *ComputerSystemResetRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type DefaultBootOrderRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultBootOrderRequest) Reset()         { *m = DefaultBootOrderRequest{} }
func (m *DefaultBootOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultBootOrderRequest) ProtoMessage()    {}
func (*DefaultBootOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{3}
}

func (m *DefaultBootOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultBootOrderRequest.Unmarshal(m, b)
}
func (m *DefaultBootOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultBootOrderRequest.Marshal(b, m, deterministic)
}
func (m *DefaultBootOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultBootOrderRequest.Merge(m, src)
}
func (m *DefaultBootOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultBootOrderRequest.Size(m)
}
func (m *DefaultBootOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultBootOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultBootOrderRequest proto.InternalMessageInfo

func (m *DefaultBootOrderRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *DefaultBootOrderRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

type BiosSettingsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiosSettingsRequest) Reset()         { *m = BiosSettingsRequest{} }
func (m *BiosSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*BiosSettingsRequest) ProtoMessage()    {}
func (*BiosSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{4}
}

func (m *BiosSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiosSettingsRequest.Unmarshal(m, b)
}
func (m *BiosSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiosSettingsRequest.Marshal(b, m, deterministic)
}
func (m *BiosSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiosSettingsRequest.Merge(m, src)
}
func (m *BiosSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_BiosSettingsRequest.Size(m)
}
func (m *BiosSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiosSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiosSettingsRequest proto.InternalMessageInfo

func (m *BiosSettingsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *BiosSettingsRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *BiosSettingsRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type BootOrderSettingsRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,3,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootOrderSettingsRequest) Reset()         { *m = BootOrderSettingsRequest{} }
func (m *BootOrderSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*BootOrderSettingsRequest) ProtoMessage()    {}
func (*BootOrderSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{5}
}

func (m *BootOrderSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootOrderSettingsRequest.Unmarshal(m, b)
}
func (m *BootOrderSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootOrderSettingsRequest.Marshal(b, m, deterministic)
}
func (m *BootOrderSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootOrderSettingsRequest.Merge(m, src)
}
func (m *BootOrderSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_BootOrderSettingsRequest.Size(m)
}
func (m *BootOrderSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootOrderSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootOrderSettingsRequest proto.InternalMessageInfo

func (m *BootOrderSettingsRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *BootOrderSettingsRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *BootOrderSettingsRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

type VolumeRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	StorageInstance      string   `protobuf:"bytes,3,opt,name=StorageInstance,proto3" json:"StorageInstance,omitempty"`
	VolumeID             string   `protobuf:"bytes,4,opt,name=VolumeID,proto3" json:"VolumeID,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,5,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeRequest) Reset()         { *m = VolumeRequest{} }
func (m *VolumeRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeRequest) ProtoMessage()    {}
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ab81854de2944a4, []int{6}
}

func (m *VolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeRequest.Unmarshal(m, b)
}
func (m *VolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeRequest.Marshal(b, m, deterministic)
}
func (m *VolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeRequest.Merge(m, src)
}
func (m *VolumeRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeRequest.Size(m)
}
func (m *VolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeRequest proto.InternalMessageInfo

func (m *VolumeRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *VolumeRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *VolumeRequest) GetStorageInstance() string {
	if m != nil {
		return m.StorageInstance
	}
	return ""
}

func (m *VolumeRequest) GetVolumeID() string {
	if m != nil {
		return m.VolumeID
	}
	return ""
}

func (m *VolumeRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSystemsRequest)(nil), "GetSystemsRequest")
	proto.RegisterType((*SystemsResponse)(nil), "SystemsResponse")
	proto.RegisterMapType((map[string]string)(nil), "SystemsResponse.HeaderEntry")
	proto.RegisterType((*ComputerSystemResetRequest)(nil), "ComputerSystemResetRequest")
	proto.RegisterType((*DefaultBootOrderRequest)(nil), "DefaultBootOrderRequest")
	proto.RegisterType((*BiosSettingsRequest)(nil), "BiosSettingsRequest")
	proto.RegisterType((*BootOrderSettingsRequest)(nil), "BootOrderSettingsRequest")
	proto.RegisterType((*VolumeRequest)(nil), "VolumeRequest")
}

func init() { proto.RegisterFile("systems/systems.proto", fileDescriptor_3ab81854de2944a4) }

var fileDescriptor_3ab81854de2944a4 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x75, 0x52, 0x60, 0x92, 0xd2, 0x32, 0x09, 0xaa, 0x09, 0x08, 0x45, 0x16, 0x87, 0x9c,
	0x8c, 0x14, 0x7a, 0xe0, 0x47, 0xea, 0x21, 0x0e, 0xd0, 0x48, 0x20, 0x90, 0x0d, 0x48, 0x1c, 0xb7,
	0xc9, 0x90, 0x46, 0x75, 0xbc, 0x61, 0x77, 0x0d, 0x8a, 0x84, 0x78, 0x03, 0x9e, 0x87, 0x03, 0xaf,
	0xc2, 0xc3, 0x20, 0x7b, 0x17, 0xd7, 0x71, 0x1d, 0xa9, 0x91, 0x22, 0x4e, 0xde, 0xf9, 0x76, 0xbe,
	0x99, 0x6f, 0x57, 0xf3, 0xad, 0xe1, 0x8e, 0x5c, 0x4a, 0x45, 0x73, 0xf9, 0xc8, 0x7c, 0xbd, 0x85,
	0xe0, 0x8a, 0xbb, 0x3f, 0x2d, 0xb8, 0xfd, 0x8a, 0x54, 0xa8, 0xc1, 0x80, 0xbe, 0x24, 0x24, 0x15,
	0xba, 0xd0, 0x94, 0x24, 0xe5, 0x8c, 0xc7, 0xef, 0xf9, 0x39, 0xc5, 0x8e, 0xd5, 0xb5, 0x7a, 0x37,
	0x83, 0x15, 0x2c, 0xcd, 0x11, 0x3a, 0xfd, 0x1d, 0x13, 0x6c, 0xee, 0xec, 0xe8, 0x9c, 0x22, 0x86,
	0x07, 0x60, 0x7f, 0x08, 0x5e, 0x3b, 0x76, 0xb6, 0x95, 0x2e, 0xf1, 0x01, 0x80, 0x20, 0xc9, 0x13,
	0x31, 0xa6, 0xd1, 0xd0, 0xa9, 0x65, 0x1b, 0x05, 0xc4, 0xfd, 0x63, 0xc1, 0x7e, 0x2e, 0x46, 0x2e,
	0x78, 0x2c, 0x29, 0xe5, 0x48, 0xc5, 0x54, 0x22, 0x7d, 0x3e, 0xa1, 0x4c, 0x4b, 0x3d, 0x28, 0x20,
	0xf8, 0x10, 0xf6, 0x74, 0xf4, 0x86, 0xa4, 0x64, 0x53, 0x32, 0x52, 0x56, 0x41, 0x3c, 0x82, 0xdd,
	0x33, 0x62, 0x13, 0x12, 0x8e, 0xdd, 0xb5, 0x7b, 0x8d, 0xfe, 0x7d, 0xaf, 0xd4, 0xc7, 0x3b, 0xc9,
	0xb6, 0x5f, 0xc4, 0x4a, 0x2c, 0x03, 0x93, 0x8b, 0x08, 0xb5, 0x53, 0x3e, 0x59, 0x66, 0x4a, 0x9b,
	0x41, 0xb6, 0xee, 0x3c, 0x85, 0x46, 0x21, 0x35, 0x3d, 0xe4, 0x39, 0x2d, 0xcd, 0x1d, 0xa5, 0x4b,
	0x6c, 0x43, 0xfd, 0x2b, 0x8b, 0x92, 0x7f, 0x42, 0x74, 0xf0, 0x6c, 0xe7, 0x89, 0xe5, 0xfe, 0x80,
	0x8e, 0xcf, 0xe7, 0x8b, 0x44, 0x91, 0xd0, 0xdd, 0x03, 0x92, 0xa4, 0x36, 0xb9, 0xf6, 0x0e, 0xdc,
	0xd0, 0xcc, 0xd1, 0xd0, 0x94, 0xcf, 0x63, 0xec, 0x42, 0xc3, 0x94, 0x1a, 0xa4, 0x9a, 0xed, 0x4c,
	0x73, 0x11, 0x72, 0x3f, 0xc1, 0xe1, 0x90, 0x3e, 0xb3, 0x24, 0x52, 0x03, 0xce, 0xd5, 0x5b, 0x31,
	0x21, 0xb1, 0xa5, 0xe6, 0xee, 0x37, 0x68, 0x0d, 0x66, 0x5c, 0x86, 0xa4, 0xd4, 0x2c, 0x9e, 0x16,
	0x47, 0x29, 0xac, 0x28, 0x1b, 0x6e, 0xef, 0x4c, 0xdf, 0xc1, 0xc9, 0x0f, 0xf3, 0xff, 0xbb, 0xff,
	0xb2, 0x60, 0xef, 0x23, 0x8f, 0x92, 0x39, 0x6d, 0xab, 0x67, 0x0f, 0xf6, 0x43, 0xc5, 0x05, 0x9b,
	0xd2, 0x28, 0x96, 0x8a, 0xc5, 0x63, 0x32, 0x06, 0x2a, 0xc3, 0x69, 0x15, 0xdd, 0x3a, 0xb7, 0x52,
	0x1e, 0x97, 0x95, 0xd7, 0x2f, 0x29, 0xef, 0xff, 0xae, 0xc1, 0x75, 0x63, 0x01, 0x3c, 0x86, 0xf6,
	0xc5, 0x2b, 0xe0, 0xf3, 0x28, 0xa2, 0xb1, 0x9a, 0xf1, 0x18, 0xd1, 0xbb, 0xf4, 0x38, 0x74, 0x0e,
	0xca, 0xc6, 0x71, 0xaf, 0xe1, 0xf3, 0xc2, 0x2b, 0x12, 0x18, 0x37, 0x5f, 0x99, 0x7c, 0x04, 0x70,
	0x91, 0x78, 0x65, 0xd6, 0x4b, 0x68, 0x55, 0x58, 0x09, 0xef, 0x79, 0xeb, 0x0d, 0x56, 0x59, 0xc7,
	0x87, 0x56, 0x48, 0xaa, 0xec, 0x0a, 0x74, 0xbc, 0x35, 0x46, 0xa9, 0x2c, 0x72, 0x0c, 0xe8, 0x9f,
	0xb1, 0x78, 0x4a, 0x45, 0x0b, 0x60, 0xdb, 0xab, 0x70, 0x44, 0x25, 0xff, 0x04, 0x0e, 0x0d, 0xbf,
	0x3c, 0xc9, 0x78, 0xd7, 0x5b, 0x37, 0xdd, 0x95, 0x95, 0xfa, 0xd0, 0xf4, 0x05, 0x31, 0x45, 0x7a,
	0x12, 0xf0, 0x96, 0xb7, 0x32, 0x9d, 0xeb, 0x38, 0x43, 0x8a, 0x68, 0x13, 0xce, 0xe9, 0x6e, 0xf6,
	0xff, 0x78, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xcf, 0xa8, 0xd6, 0x58, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemsClient is the client API for Systems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemsClient interface {
	GetSystemsCollection(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	GetSystemResource(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	GetSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	ComputerSystemReset(ctx context.Context, in *ComputerSystemResetRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	SetDefaultBootOrder(ctx context.Context, in *DefaultBootOrderRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	ChangeBiosSettings(ctx context.Context, in *BiosSettingsRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	ChangeBootOrderSettings(ctx context.Context, in *BootOrderSettingsRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
	DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*SystemsResponse, error)
}

type systemsClient struct {
	cc *grpc.ClientConn
}

func NewSystemsClient(cc *grpc.ClientConn) SystemsClient {
	return &systemsClient{cc}
}

func (c *systemsClient) GetSystemsCollection(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/GetSystemsCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) GetSystemResource(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/GetSystemResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) GetSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/GetSystems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) ComputerSystemReset(ctx context.Context, in *ComputerSystemResetRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/ComputerSystemReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) SetDefaultBootOrder(ctx context.Context, in *DefaultBootOrderRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/SetDefaultBootOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) ChangeBiosSettings(ctx context.Context, in *BiosSettingsRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/ChangeBiosSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) ChangeBootOrderSettings(ctx context.Context, in *BootOrderSettingsRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/ChangeBootOrderSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/CreateVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemsClient) DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*SystemsResponse, error) {
	out := new(SystemsResponse)
	err := c.cc.Invoke(ctx, "/Systems/DeleteVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemsServer is the server API for Systems service.
type SystemsServer interface {
	GetSystemsCollection(context.Context, *GetSystemsRequest) (*SystemsResponse, error)
	GetSystemResource(context.Context, *GetSystemsRequest) (*SystemsResponse, error)
	GetSystems(context.Context, *GetSystemsRequest) (*SystemsResponse, error)
	ComputerSystemReset(context.Context, *ComputerSystemResetRequest) (*SystemsResponse, error)
	SetDefaultBootOrder(context.Context, *DefaultBootOrderRequest) (*SystemsResponse, error)
	ChangeBiosSettings(context.Context, *BiosSettingsRequest) (*SystemsResponse, error)
	ChangeBootOrderSettings(context.Context, *BootOrderSettingsRequest) (*SystemsResponse, error)
	CreateVolume(context.Context, *VolumeRequest) (*SystemsResponse, error)
	DeleteVolume(context.Context, *VolumeRequest) (*SystemsResponse, error)
}

// UnimplementedSystemsServer can be embedded to have forward compatible implementations.
type UnimplementedSystemsServer struct {
}

func (*UnimplementedSystemsServer) GetSystemsCollection(ctx context.Context, req *GetSystemsRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemsCollection not implemented")
}
func (*UnimplementedSystemsServer) GetSystemResource(ctx context.Context, req *GetSystemsRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemResource not implemented")
}
func (*UnimplementedSystemsServer) GetSystems(ctx context.Context, req *GetSystemsRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystems not implemented")
}
func (*UnimplementedSystemsServer) ComputerSystemReset(ctx context.Context, req *ComputerSystemResetRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputerSystemReset not implemented")
}
func (*UnimplementedSystemsServer) SetDefaultBootOrder(ctx context.Context, req *DefaultBootOrderRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultBootOrder not implemented")
}
func (*UnimplementedSystemsServer) ChangeBiosSettings(ctx context.Context, req *BiosSettingsRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBiosSettings not implemented")
}
func (*UnimplementedSystemsServer) ChangeBootOrderSettings(ctx context.Context, req *BootOrderSettingsRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBootOrderSettings not implemented")
}
func (*UnimplementedSystemsServer) CreateVolume(ctx context.Context, req *VolumeRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (*UnimplementedSystemsServer) DeleteVolume(ctx context.Context, req *VolumeRequest) (*SystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}

func RegisterSystemsServer(s *grpc.Server, srv SystemsServer) {
	s.RegisterService(&_Systems_serviceDesc, srv)
}

func _Systems_GetSystemsCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).GetSystemsCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/GetSystemsCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).GetSystemsCollection(ctx, req.(*GetSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_GetSystemResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).GetSystemResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/GetSystemResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).GetSystemResource(ctx, req.(*GetSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_GetSystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).GetSystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/GetSystems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).GetSystems(ctx, req.(*GetSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_ComputerSystemReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputerSystemResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).ComputerSystemReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/ComputerSystemReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).ComputerSystemReset(ctx, req.(*ComputerSystemResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_SetDefaultBootOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultBootOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).SetDefaultBootOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/SetDefaultBootOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).SetDefaultBootOrder(ctx, req.(*DefaultBootOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_ChangeBiosSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiosSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).ChangeBiosSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/ChangeBiosSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).ChangeBiosSettings(ctx, req.(*BiosSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_ChangeBootOrderSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootOrderSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).ChangeBootOrderSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/ChangeBootOrderSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).ChangeBootOrderSettings(ctx, req.(*BootOrderSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/CreateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).CreateVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Systems_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Systems/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).DeleteVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Systems_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Systems",
	HandlerType: (*SystemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemsCollection",
			Handler:    _Systems_GetSystemsCollection_Handler,
		},
		{
			MethodName: "GetSystemResource",
			Handler:    _Systems_GetSystemResource_Handler,
		},
		{
			MethodName: "GetSystems",
			Handler:    _Systems_GetSystems_Handler,
		},
		{
			MethodName: "ComputerSystemReset",
			Handler:    _Systems_ComputerSystemReset_Handler,
		},
		{
			MethodName: "SetDefaultBootOrder",
			Handler:    _Systems_SetDefaultBootOrder_Handler,
		},
		{
			MethodName: "ChangeBiosSettings",
			Handler:    _Systems_ChangeBiosSettings_Handler,
		},
		{
			MethodName: "ChangeBootOrderSettings",
			Handler:    _Systems_ChangeBootOrderSettings_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _Systems_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _Systems_DeleteVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "systems/systems.proto",
}
